// Sample articles data - will be replaced with AI-generated content
export const sampleArticles = [
  {
    id: 'chatgpt-vs-claude-comparison',
    title: 'ChatGPT vs Claude: Which AI Assistant Dominates in 2024?',
    summary: 'Comprehensive comparison of the two leading AI assistants. Performance, pricing, features, and use cases analyzed.',
    content: 'Full article content will be generated by AI...',
    category: 'AI Comparisons',
    date: '2024-01-15',
    tags: ['chatgpt', 'claude', 'ai-assistants', 'comparison']
  },
  {
    id: 'best-free-ai-tools',
    title: '27 Best Free AI Tools You Should Be Using in 2024',
    summary: 'Discover powerful free AI tools for writing, design, coding, and productivity. No credit card required.',
    content: 'Full article content will be generated by AI...',
    category: 'AI Tools',
    date: '2024-01-14',
    tags: ['free-tools', 'ai-apps', 'productivity']
  },
  {
    id: 'ai-for-beginners-guide',
    title: 'AI for Beginners: Complete Guide to Getting Started',
    summary: 'Step-by-step guide for absolute beginners. Learn how to use AI tools effectively from day one.',
    content: 'Full article content will be generated by AI...',
    category: 'Tutorials',
    date: '2024-01-13',
    tags: ['beginners', 'tutorial', 'guide']
  }
]

export async function getArticles() {
  // This will eventually fetch from database or AI generator
  // For now, return sample data
  return sampleArticles
}

export async function getArticleById(id) {
  const articles = await getArticles()
  return articles.find(article => article.id === id)
}
