// Simple in-memory storage for articles (will persist between requests in serverless)
let articlesCache = [
  {
    id: 'chatgpt-vs-claude-comparison',
    title: 'ChatGPT vs Claude: Which AI Assistant Dominates in 2024?',
    summary: 'Comprehensive comparison of the two leading AI assistants. Performance, pricing, features, and use cases analyzed.',
    content: 'This article is being generated by our AI system. Please check back shortly for the full comparison!',
    category: 'AI Comparisons',
    date: '2024-01-15',
    tags: ['chatgpt', 'claude', 'ai-assistants', 'comparison']
  },
  {
    id: 'best-free-ai-tools',
    title: '27 Best Free AI Tools You Should Be Using in 2024',
    summary: 'Discover powerful free AI tools for writing, design, coding, and productivity. No credit card required.',
    content: 'Our AI is currently researching and compiling the most comprehensive list of free AI tools available.',
    category: 'AI Tools',
    date: '2024-01-14',
    tags: ['free-tools', 'ai-apps', 'productivity']
  }
]

// Store generated articles globally
let generatedArticles = [...articlesCache]

export async function getArticles() {
  // Return both cached and generated articles
  return [...generatedArticles]
}

export async function getArticleById(id) {
  const allArticles = await getArticles()
  return allArticles.find(article => article.id === id)
}

export async function generateNewContent() {
  try {
    console.log('Starting AI content generation...')
    
    // Simulate AI content generation (replace with actual AI call)
    const newArticle = {
      id: `ai-generated-${Date.now()}`,
      title: 'AI Tools Revolution: What to Expect in 2024',
      summary: 'Explore the latest trends and developments in AI tools and technology for 2024.',
      content: 'This is AI-generated content that will appear on your website automatically.',
      category: 'AI News',
      date: new Date().toISOString().split('T')[0],
      tags: ['trends', '2024', 'innovation']
    }
    
    // Add to generated articles
    generatedArticles.unshift(newArticle)
    
    console.log('AI content generated successfully')
    return generatedArticles
    
  } catch (error) {
    console.error('Error generating content:', error)
    return generatedArticles
  }
}

// Function to manually add articles (for testing)
export function addArticle(article) {
  generatedArticles.unshift(article)
  return generatedArticles
}
